trigger: none

pool:
  vmImage: 'ubuntu-18.04'

variables:
  webappPath: 'src/webapps/contoso'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: '6.0.x'
    includePreviewVersions: true # Required for preview versions

- task: DotNetCoreCLI@2
  displayName: 'Building'
  inputs:
    command: 'build'
    projects: '$(webappPath)/contoso.csproj'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure SDK Developer Playground(faa080af-c1d8-40ad-9cce-e1a450ca5b57)'
    appType: 'webApp'
    appName: 'azhangtestwebapp'
    package: '$(webappPath)/C:\Github\Sandbox\playground\src\webapps\contoso\bin\Debug\net6.0'
    deploymentMethod: 'auto'