name: Dogfood day issues
title: "[Dogfood Days]"
description: Report errors, suggestions, or unexpected behaviors.
labels: [Dogfood Days]

body:
  - type: markdown
    attributes:
      value: >
        Thanks for reporting. Please pick an area first from the list below:
  - type: markdown
    attributes:
      value: >
        - [ ] Bugs
  - type: markdown
    attributes:
      value: >
        - [ ] Feature Request / Suggestion
  - type: markdown
    attributes:
      value: >
        - [ ] Questions
  - type: markdown
    attributes:
      value: >
        - [ ] Other
  - type: textarea
    attributes:
      label: Issue details
      description: >
        Please describe the issue and expected result.
  - type: textarea
    attributes:
      label: CADL examples
      description: >
        Please share any relevant CADL code.
  - type: textarea
    attributes:
      label: Swagger examples
      description: >
        Please share any relevant swaggers.
