// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated />

using System;
using System.Collections.Generic;
using System.Security.Policy;
using Cadl.ProviderHubController.Common;

namespace Microsoft.PlayFab.Service.Models {
    /// <summary>
    /// The properties of a player database. 
    /// </summary>
    public partial class PlayerDatabaseProperties {
        /// <summary>
        ///  The user id for this player database 
        /// </summary>
        public string UserId { get; set; }

        /// <summary>
        ///  The set of titles belonging to this player database. 
        /// </summary>
        [Pattern (@"\/subscriptions\/[a-z0-9\-]+\/resourceGroups\/[^\/]+\/providers\/Microsoft\.PlayFab\/titles\/[^\/]+")]
        public string[] Titles { get; set; }

        /// <summary>
        ///  The provisioning state of the resource. 
        /// </summary>
        public string ProvisioningState { get; set; }

        [Added (OnVersion = "2022-01-01")]
        [Removed (OnVersion = "2022-03-01")]
        public string Color { get; set; }

        [Added (OnVersion = "2022-03-01")]
        public int? Weight { get; set; }

        public ScoringFunction Function { get; set; }
    }
}