// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated />

using Cadl.ProviderHubController.Common;
using System;
using System.Security.Policy;
using System.Collections.Generic; 

namespace Microsoft.PlayFab.Service.Models
{
    /// <summary>
    /// The properties of a title. 
    /// </summary>
    public class TitleProperties 
    {
        /// <summary>
        ///  The player database for this title 
        /// </summary>
        public string ParentDatabase { get; set; }

        /// <summary>
        ///  The provisioning state of the resource. 
        /// </summary>
        public string ProvisioningState { get; set; }

    }
}
